Repository NYCPlanning/db-safegraph, pull requests merged in 2020-10, with the labels that each got.

#25 Adding a python function that calls athena and generates output
  .github/workflows/docker.yml
  Dockerfile
  recipes/_helper/__init__.py
  recipes/_helper/aws.py
  recipes/example/example.py
  requirements.txt
Labels: athena, python

#39 adding dt partition for weekly patterns
  _init/weekly_patterns.sql
  _sync/weekly_patterns.sh
Labels: athena

#55 Add weekly device counts to social distancing tables
  recipes/weekly_county_trips.py
  recipes/weekly_state_trips.py
Labels: GTGO

#67 OPS: covid hot zone poi ETL
  recipes/_helper/poi.py
  recipes/ops_weekly_nyc_poivisits.py
Labels: core_poi, request
